export const allProductsData = [
  {
    id: 1,
    productName: "Golden Apple",
    productDescription: "Fresh and juicy golden apple",
    productPrice: "1,200",
    productImage: "/images/apple.jpg",
    producttag: "New",
  },
  {
    id: 2,
    productName: "Organic Tomatoes",
    productDescription: "Locally sourced tomatoes",
    productPrice: "900",
    productImage: "/images/tomatoes.jpg",
  },
  {
    id: 3,
    productName: "Carrot Pack",
    productDescription: "Crunchy and healthy carrots",
    productPrice: "600",
    productImage: "/images/carrots.jpg",
  },
  {
    id: 4,
    productName: "Sweet Potatoes",
    productDescription: "Naturally sweet and tasty",
    productPrice: "1,300",
    productImage: "/images/sweet-potato.jpg",
  },
  {
    id: 5,
    productName: "Fresh Spinach",
    productDescription: "Rich in iron and vitamins",
    productPrice: "800",
    productImage: "/images/spinach.jpg",
    producttag: "Popular",
  },
  {
    id: 6,
    productName: "Cucumber Delight",
    productDescription: "Crisp and refreshing cucumbers",
    productPrice: "500",
    productImage: "/images/cucumber.jpg",
    producttag: "Best Seller",
  },
  {
    id: 7,
    productName: "Bell Peppers",
    productDescription: "Colorful and flavorful bell peppers",
    productPrice: "700",
    productImage: "/images/bell-peppers.jpg",
    producttag: "New",
  },
  {
    id: 8,
    productName: "Zucchini",
    productDescription: "Versatile and nutritious zucchini",
    productPrice: "650",
    productImage: "/images/zucchini.jpg",
    producttag: "Organic",
  },
  {
    id: 9,
    productName: "Red Onions",
    productDescription: "Sharp and spicy red onions",
    productPrice: "400",
    productImage: "/images/red-onion.jpg",
  },
  {
    id: 10,
    productName: "Lettuce Leaves",
    productDescription: "Crispy lettuce for salads",
    productPrice: "450",
    productImage: "/images/lettuce.jpg",
    producttag: "Fresh",
  },
  {
    id: 11,
    productName: "Avocados",
    productDescription: "Creamy and nutritious avocados",
    productPrice: "1,000",
    productImage: "/images/avocado.jpg",
    producttag: "Best Seller",
  },
  {
    id: 12,
    productName: "Bananas",
    productDescription: "Sweet ripe bananas",
    productPrice: "750",
    productImage: "/images/banana.jpg",
  },
  {
    id: 13,
    productName: "Yam Tubers",
    productDescription: "Starchy and filling yams",
    productPrice: "2,000",
    productImage: "/images/yam.jpg",
  },
  {
    id: 14,
    productName: "Pineapple",
    productDescription: "Tropical juicy pineapples",
    productPrice: "1,500",
    productImage: "/images/pineapple.jpg",
    producttag: "New",
  },
  {
    id: 15,
    productName: "Green Beans",
    productDescription: "Freshly picked green beans",
    productPrice: "650",
    productImage: "/images/green-beans.jpg",
  },
  {
    id: 16,
    productName: "Irish Potatoes",
    productDescription: "Great for fries and stews",
    productPrice: "1,100",
    productImage: "/images/irish-potato.jpg",
  },
  {
    id: 17,
    productName: "Cabbage Head",
    productDescription: "Crunchy and large cabbage",
    productPrice: "850",
    productImage: "/images/cabbage.jpg",
  },
  {
    id: 18,
    productName: "Mangoes",
    productDescription: "Juicy tropical mangoes",
    productPrice: "1,200",
    productImage: "/images/mango.jpg",
    producttag: "Seasonal",
  },
  {
    id: 19,
    productName: "Garlic Bulbs",
    productDescription: "Strong and healthy garlic",
    productPrice: "400",
    productImage: "/images/garlic.jpg",
  },
  {
    id: 20,
    productName: "Ginger Root",
    productDescription: "Spicy and medicinal ginger",
    productPrice: "550",
    productImage: "/images/ginger.jpg",
  },
  {
    id: 21,
    productName: "Okra Fingers",
    productDescription: "Slimy but healthy okra",
    productPrice: "500",
    productImage: "/images/okra.jpg",
  },
  {
    id: 22,
    productName: "Tangerines",
    productDescription: "Sweet and tangy citrus",
    productPrice: "1,000",
    productImage: "/images/tangerine.jpg",
  },
  {
    id: 23,
    productName: "Coconut",
    productDescription: "Rich and crunchy coconut",
    productPrice: "800",
    productImage: "/images/coconut.jpg",
  },
  {
    id: 24,
    productName: "Green Apple",
    productDescription: "Tart and juicy green apples",
    productPrice: "1,300",
    productImage: "/images/green-apple.jpg",
  },
  {
    id: 25,
    productName: "Beetroot",
    productDescription: "Rich in antioxidants",
    productPrice: "950",
    productImage: "/images/beetroot.jpg",
  },
  {
    id: 26,
    productName: "Watermelon",
    productDescription: "Refreshing and hydrating",
    productPrice: "1,800",
    productImage: "/images/watermelon.jpg",
    producttag: "Hot",
  },
  {
    id: 27,
    productName: "Pumpkin",
    productDescription: "Nutritious for soups",
    productPrice: "1,000",
    productImage: "/images/pumpkin.jpg",
  },
  {
    id: 28,
    productName: "Lime",
    productDescription: "Zesty citrus limes",
    productPrice: "300",
    productImage: "/images/lime.jpg",
  },
  {
    id: 29,
    productName: "Pear",
    productDescription: "Soft and sweet pear fruit",
    productPrice: "950",
    productImage: "/images/pear.jpg",
  },
  {
    id: 30,
    productName: "Bitterleaf",
    productDescription: "Local leafy vegetable",
    productPrice: "700",
    productImage: "/images/bitterleaf.jpg",
  },
  {
    id: 31,
    productName: "Scent Leaf",
    productDescription: "Aromatic local herb",
    productPrice: "650",
    productImage: "/images/scent-leaf.jpg",
  },
  {
    id: 32,
    productName: "Chili Peppers",
    productDescription: "Spicy and hot chili",
    productPrice: "500",
    productImage: "/images/chili.jpg",
  },
  {
    id: 33,
    productName: "Green Peas",
    productDescription: "Perfect for jollof rice",
    productPrice: "750",
    productImage: "/images/green-peas.jpg",
  },
  {
    id: 34,
    productName: "Okazi Leaf",
    productDescription: "Traditional soup leaf",
    productPrice: "900",
    productImage: "/images/okazi.jpg",
  },
  {
    id: 35,
    productName: "Apple Pear",
    productDescription: "Hybrid sweet variety",
    productPrice: "1,050",
    productImage: "/images/apple-pear.jpg",
  },
  {
    id: 36,
    productName: "Dates",
    productDescription: "Sweet and chewy dates",
    productPrice: "1,400",
    productImage: "/images/dates.jpg",
  },
  {
    id: 37,
    productName: "Ugu Leaf",
    productDescription: "Common in vegetable soups",
    productPrice: "750",
    productImage: "/images/ugu.jpg",
  },
  {
    id: 38,
    productName: "Strawberries",
    productDescription: "Delicious red berries",
    productPrice: "1,600",
    productImage: "/images/strawberry.jpg",
    producttag: "Imported",
  },
];
