"""Add customer info to order

Revision ID: 5b070e1bad9f
Revises: 7dcfb935e619
Create Date: 2025-06-13 05:09:29.676073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b070e1bad9f'
down_revision = '7dcfb935e619'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_email', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('customer_phone', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('customer_phone')
        batch_op.drop_column('customer_email')
        batch_op.drop_column('customer_name')

    # ### end Alembic commands ###
